all: Poblaciones_28_20.dat	Poblaciones_26_20.dat	Poblaciones_24_20.dat	Poblaciones_22_20.dat	Poblaciones_20_20.dat	Poblaciones_18_20.dat	Poblaciones_16_20.dat	Poblaciones_14_20.dat	Poblaciones_12_20.dat	Poblaciones_10_20.dat	Poblaciones_8_20.dat	Poblaciones_6_20.dat	Poblaciones_4_20.dat	Poblaciones_2_20.dat	Poblaciones_0_20.dat:

Poblaciones_28_20.dat:  runge_kutta.x
	./runge_kutta.x 28 20
Poblaciones_26_20.dat: runge_kutta.x
	./runge_kutta.x 26 20
Poblaciones_24_20.dat: runge_kutta.x
	./runge_kutta.x 24 20
Poblaciones_22_20.dat: runge_kutta.x
	./runge_kutta.x 22 20
Poblaciones_20_20.dat: runge_kutta.x
	./runge_kutta.x 20 20
Poblaciones_18_20.dat: runge_kutta.x
	./runge_kutta.x 18 20
Poblaciones_16_20.dat: runge_kutta.x
	./runge_kutta.x 16 20
Poblaciones_14_20.dat: runge_kutta.x
	./runge_kutta.x 14 20
Poblaciones_12_20.dat: runge_kutta.x
	./runge_kutta.x 12 20
Poblaciones_10_20.dat: runge_kutta.x
	./runge_kutta.x 10 20
Poblaciones_8_20.dat: runge_kutta.x
	./runge_kutta.x 8 20